modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Random%20Mob%20Effects"
logoFile="icon.png"

[[mods]]
modId="randommobeffects"
version="3.1"
displayName="Random Mob Effects"
displayURL="https://curseforge.com/minecraft/mc-mods/random-mob-effects"
authors="Rick South"
description='''Randomly assigns a potion effect to all hostile mobs in the world. With blacklist and modded effects supported.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.randommobeffects]]
    modId="collective"
    mandatory=true
    versionRange="[6.45,)"
    ordering="NONE"
    side="BOTH"